spring:
  application:
    name: inventoryService

  datasource:
    url:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username:
    password:

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true